version: '2'

services:
  spring:
    restart: always
    build: ./src/main/docker
    links:
      - db
    ports:
      - "8080:8080"
    volumes:
      - springfiles:/tmp
      - uploads:/uploads

  db:
    restart: always
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: strongp@ssw0RD
       MYSQL_DATABASE: clippr
       MYSQL_USER: clippruser
       MYSQL_PASSWORD: clippr
    volumes:
      - mysql:/var/lib/mysql

    ports:
      - "3306:3306"

volumes:

  mysql:
    driver: local

  springfiles:
    driver: local

  uploads:
    driver: local
